[package]
name = "gw2lib-model"
version = "0.1.0"
authors = ["Greaka <cargo@greaka.de>"]
edition = "2021"
workspace = "../"

[lib]
name = "gw2lib_model"
path = "src/lib.rs"

[dependencies.either]
version = "1.6.1"
features = ["serde"]

[dependencies.serde]
version = "1.0.137"
features = [
    "derive"
]
