[package]
name = "gw2api-model"
version = "0.1.0"
authors = ["Greaka <cargo@greaka.de>"]
edition = "2021"
workspace = "../"

[dependencies.serde]
version = "1"
features = [
    "derive"
]
