[package]
name = "gw2api-model"
version = "0.1.0"
authors = ["Greaka <cargo@greaka.de>"]
edition = "2021"
workspace = "../"

[dependencies.either]
version = "1.6.1"
features = ["serde"]

[dependencies.serde]
version = "1.0.136"
features = [
    "derive"
]
