[package]
name = "gw2lib"
version = "1.1.0"
edition = "2021"
workspace = "../"
description = "A simple to use Gw2 API wrapper library"
repository = "https://github.com/greaka/gw2lib"
categories = ["api-bindings"]
keywords = ["api", "guild-wars-2", "gw2", "wrapper", "async"]
readme = "../README.md"
license = "MIT/Apache-2.0"

[lib]
name = "gw2lib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.19"
fxhash = "0.2.1"
serde = "1.0.137"
thiserror = "1.0.31"
async-trait = "0.1.56"
either = "1.6.1"
futures = "0.3.21"
serde_json = "1.0.81"
static_init = "1.0.2"
urlencoding = "2.1.0"

[dependencies.tokio]
version = "1.19.2"
default-features = false
features = ["sync", "rt", "time"]

[dependencies.hyper]
version = "0.14.19"
default-features = false
features = ["runtime", "http1", "client"]

[dependencies.hyper-rustls]
version = "0.23.0"
default-features = false
features = ["http1", "native-tokio", "logging", "tls12"]

[dependencies.gw2lib-model]
version = "1.1"
path = "../model"

[features]
blocking = []
