[package]
name = "gw2api-http"
version = "0.1.0"
edition = "2021"
workspace = "../"

[dependencies]
chrono = "0.4.19"
fxhash = "0.2.1"
serde = "1.0.136"
bus = "2.2.3"
either = "1.6.1"
rayon = "1.5.2"
parking_lot = "0.12.0"
thiserror = "1.0.30"

[dependencies.ureq]
version = "2.4.0"
features = ["json"]

[dependencies.gw2api-model]
path = "../model"
