'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 5 * * *'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set Current Date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ steps.date.outputs.week_of_year }}
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: target
          key: cargo-build-target-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: proxy/target
          key: cargo-build-target-${{ hashFiles('proxy/Cargo.lock') }}
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: "start proxy and test"
        run: |
          pushd proxy
          cargo build --release
          cargo run --release &
          prox=$!
          popd
          cargo nextest run
          cargo nextest run --run-ignored ignored-only
          kill -9 $prox
